### ISSUE TITLE
This requires apigateway:GET which ViewOnlyAccess doesn't have

### ISSUE THREAD

**Issue by rupertbg** [anirudhbiyani/findmytakeover#2]
https://github.com/anirudhbiyani/findmytakeover/blob/0af3a4d7daf2626e4a05d03eb01dd82ae1bc36bd/collector/aws.py#L93-L96

**Comment by anirudhbiyani** [comment]
This has been fixed. SecurityAudit Role is also needed for this along with ViewOnly role.
